web/apps/accueil/urls.py
from django.urls import path
from . import views

app_name = 'accueil'

urlpatterns = [
    path('', views.index, name="index"),
]

web/apps/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [

    # Authentification
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),

    # Panneau utilisateur
    path('profil/', views.user_panel, name="profil"),
    path('profil/<str:submitted_data_form>', views.user_panel, name="profil_post"),

    # Inscription
    path('inscription/<key>', views.inscription, name="inscription"),

    # Changement du mdp
    path('changer-mdp/', views.ChangerMdpView.as_view(), name="changer_mdp"),
    path('changer-mdp/success', views.changer_mdp_success, name="changer_mdp_success"),

    # Mdp oublié ?
    path('reset-mdp/', views.ResetMdpView.as_view(), name = "reset_mdp"),
    path('reset-mdp/done', views.ResetMdpDoneView.as_view(), name="reset_mdp_done"),
    path('reset-mdp/formulaire-mdp/<uidb64>/<token>/', views.ResetMdpFormView.as_view(), name="reset_mdp_formulaire"),
]

web/brassintranet/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls', namespace='users')),
    path('', include('apps.accueil.urls', namespace='accueil')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from apps.users.models import UserExtended


class LoginForm(forms.Form):
    username_email = forms.CharField(
        label="Nom d'utilisateur ou adresse mail",
        max_length=150
    )
    password = forms.CharField(
        label="Mot de passe",
        widget=forms.PasswordInput
    )


class ProfilForm(forms.ModelForm):
    class Meta:
        model = UserExtended
        fields = ('username', 'first_name', 'last_name', 'email')


class CouleurForm(forms.ModelForm):
    class Meta:
        model = UserExtended
        fields = ('couleur',)


class TokenSendForm(forms.Form):
    key = forms.CharField(
        label="Veuillez entrer la clé de votre jeton d'inscription",
        max_length=32
    )


class InscriptionForm(UserCreationForm):
    class Meta:
        model = UserExtended
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Surcharge du champ username pour interdire le caractère "@"
        self.fields['username'].help_text = "Votre nom d'utilisateur doit comporter moins de 150 caractères (lettres " \
                                            "majuscules et minuscules, chiffres, \"+\", \"-\", \"_\")"

    def clean(self):
        """
        Nettoyage du champ username.
        Le caractère "@" est désormais interdit dans le nom d'utilisateur.
        """
        cleaned_data = super().clean()
        username = cleaned_data['username']
        first_name = cleaned_data['first_name']
        if username.find('@') > -1:
            self.add_error('username', "Le caractère \"@\" est interdit pour les noms d'utilisateurs")
        if username.lower() == first_name.lower():
            self.add_error('username', "Ce surnom est claqué au sol. Veuillez en choisir un autre svp")

web/apps/users/views.py
import copy

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.views import PasswordResetDoneView, PasswordChangeView, PasswordResetConfirmView, \
    PasswordResetView
from django.db import transaction
from django.http import Http404
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy

from brassintranet import settings
from brassintranet.settings import LOGIN_REDIRECT_URL, EMAIL_HOST_USER
from .forms import LoginForm, TokenSendForm, InscriptionForm, ProfilForm, CouleurForm
from .models import UserExtended, UserCreationToken
from .tasks import send_async_email_html


# Constantes


MESSAGE_INFO_MDP_RESET_OK = "Veuillez vérifier vos emails. Si l'adresse que vous avez renseignée correspond à un " \
                            "compte existant, vous allez recevoir un lien permettant de réinitialiser votre mot " \
                            "de passe."

MESSAGE_SUCCESS_MDP_CHANGE_OK = "Votre mot de passe a été modifié avec succès !"
MESSAGE_SUCCESS_PROFIL_CHANGE_OK = "Votre profil a été modifié avec succès !"
MESSAGE_SUCCESS_SIGNUP_OK = "Votre compte a été créé avec succès !"
MESSAGE_SUCCESS_TOKEN_KEY_OK = "Votre lien d'inscription est conforme. Veuillez vous inscrire via le formulaire " \
                               "ci-dessous."

MESSAGE_WARNING_MDP_RESET_OK = "Pensez à vérifier vos courriers indésirables ! L'email de réinitialisation du mot de " \
                               "passe pourrait s'y trouver."

MESSAGE_ERROR_PROFIL_FIELD_ERRORS = "Erreur : les changements n'ont pas pu être sauvegardés car certains champs sont " \
                                    "erronés. Veuillez réessayer en apportant les correctifs nécessaires."
MESSAGE_ERROR_SIGNUP_FIELD_ERRORS = "Erreur : certains champs sont erronés, veuillez apporter les correctifs " \
                                    "nécessaires puis réessayer."
MESSAGE_ERROR_WRONG_CREDENTIALS = "Vos identifiants n'ont pas été reconnus, veuillez vérifier votre mot de passe, " \
                                  "adresse mail ou nom d'utilisateur, puis réessayez"
MESSAGE_ERROR_WRONG_TOKEN_KEY = "Erreur : La clé spécifiée dans l'URL est incorrecte"


# Méthodes utilitaires


def redirect_if_authenticated(request):
    """
    Renvoie une redirection si l'utilisateur est déjà connecté, ou False sinon (permet de tester dans la vue pour
        contrôler la valeur de retour)
    """
    if request.user.is_authenticated:
        return redirect(LOGIN_REDIRECT_URL)
    else:
        return False


def raise_404_if_no_unexpired_token(request):
    """
    Renvoie une erreur 404 s'il n'existe aucun jeton d'inscription non-expiré en base
    """
    if not UserCreationToken.objects_unexpired.exists():
        raise Http404


# Vues principales


def user_login(request):
    """
    Vue de connexion de l'utilisateur. Charge le formulaire de connexion si l'utilisateur n'est pas connecté,
        redirige vers la page d'accueil sinon.
    > Liée au template users/login.html
    """
    context_vars = {}

    # Rediriger vers la page d'accueil si on est déjà connecté
    if redirect_if_authenticated(request): return redirect_if_authenticated(request)
    else:
        # Si on arrive depuis un POST (aka un formulaire de connexion a été posté), alors on traite la demande de co
        if request.method == 'POST':
            form = LoginForm(request.POST or None)
            # Commencer la procédure d'authentification si les champs du formulaires sont bien remplis
            if form.is_valid():
                username_email = form.cleaned_data['username_email']
                password = form.cleaned_data['password']

                # Essayer de connecter l'utilisateur avec son username. Si ça ne marche pas, utiliser username_email en
                # tant qu'email pour récupérer l'utilisateur s'il existe, puis l'authentifier.
                # Si ça ne marche toujours pas, utilisateur non-reconnu => on signale une erreur
                try:
                    user_connecting = authenticate(username=username_email, password=password)

                    # Si la méthode d'authentification a trouvé un couple username/mdp qui existe, alors on connecte
                    # l'utilisateur et on le redirige vers la page d'accueil par défaut.
                    if user_connecting:
                        login(request, user_connecting)
                        return redirect(LOGIN_REDIRECT_URL)
                    # Sinon, on réessaye en considérant username_email comme un email pour récupérer l'utilisateur s'il
                    # existe.
                    else:
                        user_from_provided_email = UserExtended.objects.get(email=username_email)
                        username = user_from_provided_email.username
                        user_connecting = authenticate(username=username, password=password)

                        # Si la méthode d'authentification a trouvé un couple username/mdp qui existe, alors on connecte
                        # l'utilisateur et on le redirige vers la page d'accueil par défaut.
                        if user_connecting:
                            login(request, user_connecting)
                            return redirect(LOGIN_REDIRECT_URL)
                        else:
                            messages.error(request, MESSAGE_ERROR_WRONG_CREDENTIALS)
                except:
                    messages.error(request, MESSAGE_ERROR_WRONG_CREDENTIALS)
            else:
                messages.error(request, MESSAGE_ERROR_WRONG_CREDENTIALS)
        else:
            form = LoginForm()

        context_vars['form'] = form
        context_vars['tokens_exist'] = UserCreationToken.objects_unexpired.exists()
        return render(request, 'users/login.html', context_vars)


def user_logout(request):
    """
    Vue de déconnexion de l'utilisateur.
    > Redirige vers la page d'accueil et ainsi automatiquement vers la page de connexion
    """
    logout(request)
    return redirect(LOGIN_REDIRECT_URL)


@transaction.atomic
@staff_member_required(login_url=settings.LOGIN_URL)
def user_panel(request, submitted_data_form=''):
    """
    Vue chargeant la section des informations utilisateur
    """
    context_vars = {}
    form_in_profil = ProfilForm()  # form_in = formulaire côté interface
    form_in_couleur = CouleurForm()

    if request.method == 'POST':
        # On utilise une copie de l'utilisateur pour éviter de commit des données partiellement fausses
        buffer_user = copy.copy(request.user)

        # Récupération du formulaire en fonction du paramètre qui indique de quel formulaire on récupère les données
        if submitted_data_form == 'profil':
            form_out = ProfilForm(request.POST, instance=buffer_user)  # form_out = données du formulaire qu'on récupère
            # Formulaire à qui transmettre les erreurs = le même utilisé pour transmettre les données
            form_to_transmit_errors_to = form_in_profil
        elif submitted_data_form == 'couleur':
            form_out = CouleurForm(request.POST, instance=buffer_user)
            form_to_transmit_errors_to = form_in_couleur
        else:
            raise Http404

        if form_out.is_valid():
            # On ne modifie l'instance que si le formulaire est valide
            form_out.save()
            messages.success(request, MESSAGE_SUCCESS_PROFIL_CHANGE_OK)
        else:
            # On ne transmet que les erreurs reçues au formulaire d'entrée nouvellement chargé
            form_to_transmit_errors_to._errors = form_out._errors
            messages.error(request, MESSAGE_ERROR_PROFIL_FIELD_ERRORS)

        context_vars['form_out'] = form_out  # Pour vérifier le type de form_out dans les tests unitaires

    context_vars['form_profil'] = form_in_profil
    context_vars['form_couleur'] = form_in_couleur
    return render(request, 'users/user_panel.html', context_vars)


@transaction.atomic
def inscription(request, key):
    """
    Vue ayant les 2 fonctions suivantes :
    - Réceptionner la clé du jeton d'inscription et diriger le visiteur vers la page d'inscription si le jeton est
        reconnu.
    - Créer un compte administrateur en fonction des données entrées dans le formulaire
    > Liée au template users/inscription.html,
    > Charge le template users/token_fail.html si la clé du jeton présente dans les données de la requête POST n'a
        pas été reconnue
    > Charge le template users/inscription_réussie.html si un formulaire d'inscription valide a été envoyé
    """
    context_vars = {}

    # Retourner une erreur 404 s'il n'existe aucun token non-expiré en base
    raise_404_if_no_unexpired_token(request)
    # Rediriger vers la page d'accueil si on est déjà connecté
    if redirect_if_authenticated(request): return redirect_if_authenticated(request)
    else:
        # Récupération du jeton d'inscription depuis l'URL
        token = UserCreationToken.objects_unexpired.retrieve_token_with_key(key, True)
        # Si la clé du jeton que l'on a entré dans l'URL est valide, on charge la page d'inscription.
        if token:
            # Si cette vue a été rechargée depuis le formulaire d'inscription (ce qui veut dire qu'on a envoyé des
            # données par le biais du formulaire utilisateur) on lance la procédure de création d'utilisateur
            if request.method == 'POST':
                form = InscriptionForm(request.POST or None)

                # Si les données du formulaire sont valides, on crée l'utilisateur et on supprime le jeton
                if form.is_valid():
                    new_user = form.save(commit=False)
                    new_user.is_staff = True
                    new_user.save()

                    token.delete()

web/apps/users/templates/users/changer_mdp.html
{% extends "users/base/users.html" %}

{% block content %}

<h3>Changer votre mot de passe</h3>
<form method="post" action="">
    {% csrf_token %}
    {% include "users/forms/form_changer_mdp.html" %}
    <input type="submit" value="Envoyer" class="btn btn-primary" />
    <a href="{% url 'users:login' %}" class="btn btn-secondary">Annuler</a>
</form>

{% endblock %}

web/apps/users/templates/users/inscription.html
{% extends "users/base/users.html" %}

{% block content %}

<h3>Inscription</h3>
<small><strong>Tous les champs sont obligatoires</strong></small>
<form method="post" action="{% url 'users:inscription' key %}">
    {% csrf_token %}
    {% include "users/forms/form_inscription.html" %}
    <input type="submit" value="S'inscrire" class="btn btn-primary" />
    <a href="{% url 'users:login' %}" class="btn btn-secondary">Annuler</a>
</form>

{% endblock %}

web/apps/users/templates/users/login.html
{% extends "users/base/users.html" %}
{% load static %}

{% block content %}

<div class="mb-4">
    <img src="{% static 'svg/bdb2021_intranet_vect.svg' %}" alt="Brasserie du Bois" height="160px"/>
</div>
<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {% include "forms/form_placeholders.html" %}
    <hr/>
    <input type="submit" value="Se connecter" class="btn btn-primary" /><br/>
    <small><a href="{% url 'users:reset_mdp' %}">Mot de passe oublié ?</a></small><br/>
</form>

{% endblock %}

web/apps/users/templates/users/notification_and_homebutton.html
{% extends "users/base/users.html" %}

{% block content %}

<p><a href="{% url 'accueil:index' %}">Cliquez ici pour retourner à l'accueil</a></p>

{% endblock %}

web/apps/users/templates/users/reset_mdp.html
{% extends "users/base/users.html" %}

{% block content %}

<h3>Mot de passe oublié ?</h3>
<p>Veuillez entrer l'email associé à votre compte. Un lien de réinitialisation du mot de passe vous sera envoyé.</p>
<form method="post" action="">
    {% csrf_token %}
    {% include "forms/form_placeholders.html" %}
    <input type="submit" value="Envoyer" class="btn btn-primary" />
    <a href="{% url 'users:login' %}" class="btn btn-secondary">Annuler</a>
</form>

{% endblock %}

web/apps/users/templates/users/reset_mdp_formulaire.html
{% extends "users/base/users.html" %}

{% block content %}

<h3>Nouveau mot de passe</h3>
<form method="post" action="">
    {% csrf_token %}
    {% include "forms/form_placeholders.html" %}
    <input type="submit" value="Envoyer" class="btn btn-primary" />
</form>

{% endblock %}

web/apps/users/templates/users/token.html
{% extends "users/base/users.html" %}

{% block content %}

<h3>Utiliser un jeton d'inscription</h3>
<form method="post" action="{% url 'users:inscription' %}">
    {% csrf_token %}
    {% include "forms/form_placeholders.html" %}
    <input type="submit" value="Envoyer" class="btn btn-primary" />
    <a href="{% url 'users:login' %}" class="btn btn-secondary">Annuler</a>
</form>
{{ key }}

{% endblock %}

web/apps/users/templates/users/token_fail.html
{% extends "users/base/users.html" %}

{% block content %}

<p>Votre URL d'inscription est invalide ou a expiré. Inscription impossible.</p>

{% endblock %}

web/apps/users/templates/users/user_panel.html
{% extends "users/base/users.html" %}
{% load static %}

{% block title %}Profil - BDB{% endblock %}

{% block content %}

<div class="row">
    <div class="col-auto position-absolute" style="z-index: 1">
        <a href="/" class="btn btn-secondary">
            <img src="{% static 'svg/icons/button_back.svg' %}" alt="" height="16px"/>
        </a>
    </div>
    <div class="col text-center">
        <h1>Profil</h1>
    </div>
</div>
<hr class="mt-4"/>

<h3 >Général</h3>
<div class="row justify-content-center align-items-center">
    <a class="col-auto" style="cursor: pointer;" data-toggle="modal" data-target="#modalGeneralChangerCouleur">
        <div data-toggle="tooltip" data-placement="left" title="Changer la couleur">
            {% include 'icons_dynamic/nav_profil.svg.html' with size="128" colour=user.couleur %}
        </div>
    </a>
    <div class="col-auto text-left">
        <span class="h4">{{ user.username }}</span><br/>
        <span>{{ user.first_name }} {{ user.last_name }}</span><br/>
        <span><small>{{ user.email }}</small></span>
    </div>
</div>
<div class="row justify-content-center">
    <button class="col-10 col-sm-8 col-md-6 btn btn-primary"
            data-toggle="modal" data-target="#modalGeneralChangerInfos">
        Modifier ces informations
    </button>
</div>
<hr class="mt-4"/>

<h3>Sécurité & Accès</h3>
<div class="row justify-content-center">
    <dl>
        <dt>Rôles</dt>
        <dd>
            {% if user.is_staff %}<span class="badge badge-pill badge-primary">Staff</span>{% endif %}
            {% if user.is_superuser %}<span class="badge badge-pill badge-danger">Admin</span>{% endif %}
        </dd>
        <dt>Accès au gestionnaire d'identifiants</dt>
        <dd class="text-danger">Non</dd>
    </dl>
</div>
<div class="row justify-content-center">
    <a href="{% url 'users:changer_mdp' %}"
       class="col-10 col-sm-8 col-md-6 btn btn-warning">Modifier le mot de passe</a>
</div>

<!-- Modals -->

<div class="modal fade" id="modalGeneralChangerInfos" tabindex="-1" aria-labelledby="modalGeneralChangerInfos" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header justify-content-center">
                <h5 class="modal-title" id="exampleModalLabel">Modifier les informations du profil</h5>
            </div>
            <form method="post" action="{% url 'users:profil_post' 'profil' %}">
                <div class="modal-body">
                    {% csrf_token %}
                    {% include "users/forms/form_update_profil.html" with form=form_profil %}
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                    <input type="submit" value="Valider" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modalGeneralChangerCouleur" tabindex="-1" aria-labelledby="modalGeneralChangerCouleur" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header justify-content-center">
                <h5 class="modal-title" id="exampleModalLabel">Modifier la couleur</h5>
            </div>
            <form method="post" action="{% url 'users:profil_post' 'couleur' %}">
                <div class="row modal-body justify-content-center">
                    <div class="col-6">
                        {% csrf_token %}
                        {% include "users/forms/form_update_couleur.html" with form=form_couleur %}
                    </div>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                    <input type="submit" value="Valider" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    /**
     * Activation des tooltips sur la page
     */
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>

{% endblock %}