web/apps/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [

    # Authentification
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),

    # Panneau utilisateur
    path('profil/', views.user_panel, name="profil"),
    path('profil/<str:submitted_data_form>', views.user_panel, name="profil_post"),

    # Inscription
    path('inscription/<key>', views.inscription, name="inscription"),

    # Changement du mdp
    path('changer-mdp/', views.ChangerMdpView.as_view(), name="changer_mdp"),
    path('changer-mdp/success', views.changer_mdp_success, name="changer_mdp_success"),

    # Mdp oublié ?
    path('reset-mdp/', views.ResetMdpView.as_view(), name = "reset_mdp"),
    path('reset-mdp/done', views.ResetMdpDoneView.as_view(), name="reset_mdp_done"),
    path('reset-mdp/formulaire-mdp/<uidb64>/<token>/', views.ResetMdpFormView.as_view(), name="reset_mdp_formulaire"),
]

web/brassintranet/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls', namespace='users')),
    path('', include('apps.accueil.urls', namespace='accueil')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/alerts.html
{% if messages %}
    {% for level, class in bootstrap_message_classes.items %}
        {% for message in messages %}
            {% if message.level == level %}
            <div class="{{ class }}">
                {{ message }}
            </div>
            {% endif %}
        {% endfor %}
    {% endfor %}
{% endif %}

web/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="icon" href="{% static 'favicon.ico' %}" />
    <title>{% block title %}Intranet{% endblock %}</title>
</head>
<body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

{% block body %}


{% block navbar %}
    <header class="container-fluid sticky-top bg-danger text-white text-center">
        Erreur serveur : le contenu de la navbar n'a pas pu être chargé
    </header>
{% endblock %}


<section class="container-fluid">
    {% block content %}{% endblock %}
</section>


<footer class="container-fluid fixed-bottom bg-secondary">
    <div class="row justify-content-between">
        <div class="col-auto m-1 px-0">
            <small><ul class="list-inline mb-0">
                <li class="list-inline-item">&copy; Brasserie du Bois</li>
                <li class="list-inline-item">2020-2021</li>
                <li class="list-inline-item d-none d-lg-inline-block">Made with Django</li>
                <li class="list-inline-item d-none d-xl-inline-block">
                    Bootstrap theme : Darkly (by Thomas Park), distributed by Bootswatch, adjusted by Martin Gaboriaud
                </li>
            </ul></small>
        </div>
        <div class="col text-right pr-0">
            <ul class="list-inline mb-0">
                <li class="list-inline-item d-none d-lg-inline-block">
                    <small><strong>{{ version.name }}</strong></small>
                </li>
                <li class="list-inline-item">
                    <small><strong>v{{ version.version }}_{{ version.type }}</strong></small>
                </li>
            </ul>
        </div>
    </div>
</footer>

{% endblock %}

<script>
    /**
     * Gestion du rangement de la navbar en cas de scroll down sur téléphone (hauteur inférieure à 800px)
     */
    const MOBILE_MAX_SIZE = 800;
    const OFFSET_ON_SCROLL = "-120px";
    let prevScrollpos = window.pageYOffset;
    let zoneToHideOnScroll = $('#navbar, #bdb-nav-dropdown-container');

    window.onscroll = function() {
        if (window.innerHeight < MOBILE_MAX_SIZE) {
            var currentScrollPos = window.pageYOffset;
            if (prevScrollpos > currentScrollPos) {
                zoneToHideOnScroll.css('top', '0');
            } else {
                zoneToHideOnScroll.css('top', OFFSET_ON_SCROLL);
                let dropdowns = $('#bdb-nav-dropdown-container').children('.collapse');
                for (let dropdown of dropdowns) {
                    $(dropdown).collapse('hide');
                }
            }
            prevScrollpos = currentScrollPos;
        }
    }
</script>

<script>
    /**
     * Gestion de la fermeture automatique des autres dropdowns de la navbar lorsqu'un dropdown est ouvert
     */
    $(function() {
        $(".bdb-nav-item[data-toggle='collapse']").click(function() {
            let navItemSiblings = $(this).parent().siblings('li').children(".bdb-nav-item[data-toggle='collapse']");
            for (let sibling of navItemSiblings) {
                let dropdownSelector = $('#bdb-nav-dropdown-container ' + $(sibling).attr('href'));
                dropdownSelector.collapse('hide');
            }
        });
    })
</script>

<script>
    /**
     * Gestion du tooltip associé aux options à droite de la navbar (apparaition et mise à jour du texte)
     */
    $(function() {
        $('.bdb-nav-options-btn').on({
            mouseenter: function() {
                let tooltipSelector = $('#bdb-nav-options-tooltip');
                tooltipSelector.text($(this).attr('data-tooltip'));
                tooltipSelector.css('opacity', '1');
            },
            mouseleave: function() {
                let tooltipSelector = $('#bdb-nav-options-tooltip');
                tooltipSelector.css('opacity', '0');
            }
        });
    })
</script>

</body>
</html>

web/templates/navbar.html
{% load static %}

<!-- NAVBAR -->
<header class="container-fluid sticky-top">


    <!-- Header pour petits écrans -->
    <div class="row bdb-nav-mini-header d-md-flex d-lg-none">
        <a href="/" class="col-auto bdb-nav-mini-header-label d-none d-md-inline-flex">
            <img src="{% static 'svg/bdb2021_intranet_vect.svg' %}" alt="" class="mb-2" height="32px" />
            <span class="h3 ml-1 mb-0">brassintranet</span>
            <small class="pt-3">- Beta</small>
        </a>
        <a href="/" class="col-auto bdb-nav-mini-header-label d-sm-inline-block d-md-none px-2">
            <img src="{% static 'svg/bdb2021_intranet_vect.svg' %}" alt="" class="mb-2" height="24px" />
            <span class="h4 ml-1 mt-1">brassintranet</span>
        </a>
        <div class="col-auto bdb-nav-options align-items-center mb-1">
            <a href="/admin" class="bdb-nav-options-btn badge badge-pill badge-danger p-1">
                <img src="{% static 'svg/icons/option_admin.svg' %}" alt="" height="16px"/>
            </a>
            <a href="https://gitlab.com/mgaboriaud/brassintranet-du-bois/-/wikis/home" target="_blank"
               class="bdb-nav-options-btn badge badge-pill badge-secondary p-1">
                <img src="{% static 'svg/icons/option_aide.svg' %}" alt="" height="16px"/>
            </a>
            <a href="{% url 'users:logout' %}" class="bdb-nav-options-btn badge badge-pill badge-secondary p-1">
                <img src="{% static 'svg/icons/option_deconnexion.svg' %}" alt="" height="16px"/>
            </a>
            <span class="ml-1 mr-2 border-right border-light" style="height: 16px;"></span>
            <a href="{% url 'users:profil' %}">
                {% include 'icons_dynamic/nav_profil.svg.html' with size="32" colour=user.couleur %}
            </a>
        </div>
    </div>


    <!-- Navbar body -->
    <div class="row">
        <div class="col-md px-0">
            <nav class="d-flex navbar navbar-expand navbar-dark bg-secondary justify-content-center align-items-center"
                id="navbar">

                <!-- Brand avec titre -->
                <a class="col-auto navbar-brand align-items-center mr-0 px-2 d-none d-lg-flex" href="/">
                    <span>
                        <img src="{% static 'svg/bdb2021_intranet_vect.svg' %}" alt="" height="64px" />
                        <span class="h1 ml-1 mt-1 align-top d-none d-xl-inline-block">brassintranet</span>
                        <small class="badge badge-info ml-1 d-none d-xl-inline-block">Beta</small>
                    </span>
                    <span class="bdb-nav-brand-signature">
                        <small>by </small>
                        <img src="{% static 'svg/bdb2021_typo_white_vect.svg' %}" alt="" height="48px" />
                    </span>
                </a>

                <!-- Séparateur -->
                <span class="mx-4 my-2 border-right border-light d-none d-lg-inline-block" style="height: 64px;"></span>

                <!-- Launchers de modules -->
                <ul class="navbar-nav overflow-auto pr-0" style="flex: 0 0 initial; width: auto; max-width: 100%;">
                    {% for launcher in navbar_data.launchers %}
                    <li>
                        <a class="nav-item bdb-nav-item {% if launcher.id == active_launcher_id %}active{% endif %}"
                            href="{{ launcher.href }}"
                            {% if launcher.opens_dropdown %}
                            data-toggle="collapse" role="button" aria-expanded="false"
                            aria-controls="{{ launcher.href | cut:"#" }}"
                            {% endif %}>
                            <img class="bdb-nav-item-icon" src="{% static launcher.icone %}" alt=""/>
                            <span class="bdb-nav-item-label">{{ launcher.nom }}</span>
                        </a>
                    </li>
                    {% endfor %}
                </ul>

                <!-- Séparateur -->
                <span class="mx-4 my-2 border-right border-light d-none d-lg-inline-block" style="height: 64px;"></span>

                <!-- Section profil/options -->
                <div class="col-auto container-fluid flex-column justify-content-center align-items-end mr-5 d-none d-lg-flex">
                    <a href="{% url 'users:profil' %}" class="row bdb-nav-profile-wrapper">
                        {% include 'icons_dynamic/nav_profil.svg.html' with size="32" colour=user.couleur %}
                        <span class="bdb-nav-profile-label">{{ user.username|truncatechars:32 }}</span>
                    </a>
                    <div class="row align-items-center bdb-nav-options">
                        <small class="bdb-nav-options-tooltip mr-1 text-right" id="bdb-nav-options-tooltip"></small>
                        <a href="/admin" class="bdb-nav-options-btn badge badge-pill badge-danger mx-1 p-1"
                           data-tooltip="Administration">
                            <img src="{% static 'svg/icons/option_admin.svg' %}" alt="" height="16px"/>
                        </a>
                        <a href="https://gitlab.com/mgaboriaud/brassintranet-du-bois/-/wikis/home" target="_blank"
                           class="bdb-nav-options-btn badge badge-pill badge-dark mx-1 p-1" data-tooltip="Aide">
                            <img src="{% static 'svg/icons/option_aide.svg' %}" alt="" height="16px"/>
                        </a>
                        <a href="{% url 'users:logout' %}"
                           class="bdb-nav-options-btn badge badge-pill badge-dark mx-1 p-1" data-tooltip="Déconnexion">
                            <img src="{% static 'svg/icons/option_deconnexion.svg' %}" alt="" height="16px"/>
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </div>


    <!-- Section des dropdowns -->
    <div class="container d-flex col-12 col-lg-8 col-xl-6" id="bdb-nav-dropdown-container">
        {% for dropdown in navbar_data.dropdowns %}
        <div class="row collapse bdb-nav-dropdown-row" id="{{ dropdown.id }}">
            <div class="list-group bdb-nav-dropdown-list">
                {% for url in dropdown.urls %}
                <a href="{{ url.href }}" class="list-group-item bdb-nav-dropdown-item">
                    {{ url.titre }}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>

</header>